# Generated by Django 4.2.5 on 2023-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Craftapp', '0002_alter_user_brewery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brewery',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
