# Generated by Django 4.2.5 on 2023-10-13 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Craftapp', '0003_alter_user_brewery'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeknumber', models.CharField(blank=True, max_length=20, null=True)),
                ('participant', models.IntegerField(blank=True, null=True)),
                ('weekname', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
