# Generated by Django 4.2.5 on 2023-10-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Craftapp', '0004_weekparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
